-- Shared audio storage for cross-machine playback.
-- Uploaded files are persisted in PostgreSQL so any backend instance can stream them.

create table if not exists audio_assets (
    id bigint generated by default as identity primary key,
    stored_filename varchar(255) not null,
    original_filename varchar(255) not null,
    content_type varchar(100),
    size_bytes bigint not null,
    file_data oid not null,
    created_at timestamp with time zone not null
);

create unique index if not exists ux_audio_assets_stored_filename on audio_assets (stored_filename);
